#pragma once

#using <mscorlib.dll>
#using <System.dll>
#using <System.Xml.dll>

using namespace System::Security::Permissions;
[assembly:SecurityPermissionAttribute(SecurityAction::RequestMinimum, SkipVerification=false)];
// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
using namespace System::Xml::Serialization;
using namespace System;
ref class MensajeHacienda;


/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.8.3928.0"), 
System::SerializableAttribute, 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true, Namespace=L"https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda")]
public enum class MensajeHaciendaTipoIdentificacionEmisor {
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"01")]
    Item01,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"02")]
    Item02,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"03")]
    Item03,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"04")]
    Item04,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"05")]
    Item05,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"06")]
    Item06,
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.8.3928.0"), 
System::SerializableAttribute, 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true, Namespace=L"https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda")]
public enum class MensajeHaciendaTipoIdentificacionReceptor {
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"01")]
    Item01,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"02")]
    Item02,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"03")]
    Item03,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"04")]
    Item04,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"05")]
    Item05,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"06")]
    Item06,
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.8.3928.0"), 
System::SerializableAttribute, 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true, Namespace=L"https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda")]
public enum class MensajeHaciendaMensaje {
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"1")]
    Item1,
    
    /// <remarks/>
    [System::Xml::Serialization::XmlEnumAttribute(L"3")]
    Item3,
};

/// <remarks/>
[System::CodeDom::Compiler::GeneratedCodeAttribute(L"xsd", L"4.8.3928.0"), 
System::SerializableAttribute, 
System::Diagnostics::DebuggerStepThroughAttribute, 
System::ComponentModel::DesignerCategoryAttribute(L"code"), 
System::Xml::Serialization::XmlTypeAttribute(AnonymousType=true, Namespace=L"https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda"), 
System::Xml::Serialization::XmlRootAttribute(Namespace=L"https://cdn.comprobanteselectronicos.go.cr/xml-schemas/v4.4/mensajeHacienda", 
IsNullable=false)]
public ref class MensajeHacienda {
    
    private: System::String^  claveField;
    
    private: System::String^  nombreEmisorField;
    
    private: MensajeHaciendaTipoIdentificacionEmisor tipoIdentificacionEmisorField;
    
    private: System::String^  numeroCedulaEmisorField;
    
    private: System::String^  nombreReceptorField;
    
    private: System::Nullable<MensajeHaciendaTipoIdentificacionReceptor > tipoIdentificacionReceptorField;
    
    private: System::Boolean tipoIdentificacionReceptorFieldSpecified;
    
    private: System::String^  numeroCedulaReceptorField;
    
    private: MensajeHaciendaMensaje mensajeField;
    
    private: System::String^  detalleMensajeField;
    
    private: System::Decimal montoTotalImpuestoField;
    
    private: System::Boolean montoTotalImpuestoFieldSpecified;
    
    private: System::Decimal totalFacturaField;
    
    /// <remarks/>
    public: property System::String^  Clave {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: property System::String^  NombreEmisor {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: property MensajeHaciendaTipoIdentificacionEmisor TipoIdentificacionEmisor {
        MensajeHaciendaTipoIdentificacionEmisor get();
        System::Void set(MensajeHaciendaTipoIdentificacionEmisor value);
    }
    
    /// <remarks/>
    public: property System::String^  NumeroCedulaEmisor {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: property System::String^  NombreReceptor {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
    property System::Nullable<MensajeHaciendaTipoIdentificacionReceptor > TipoIdentificacionReceptor {
        System::Nullable<MensajeHaciendaTipoIdentificacionReceptor > get();
        System::Void set(System::Nullable<MensajeHaciendaTipoIdentificacionReceptor > value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlIgnoreAttribute]
    property System::Boolean TipoIdentificacionReceptorSpecified {
        System::Boolean get();
        System::Void set(System::Boolean value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlElementAttribute(IsNullable=true)]
    property System::String^  NumeroCedulaReceptor {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: property MensajeHaciendaMensaje Mensaje {
        MensajeHaciendaMensaje get();
        System::Void set(MensajeHaciendaMensaje value);
    }
    
    /// <remarks/>
    public: property System::String^  DetalleMensaje {
        System::String^  get();
        System::Void set(System::String^  value);
    }
    
    /// <remarks/>
    public: property System::Decimal MontoTotalImpuesto {
        System::Decimal get();
        System::Void set(System::Decimal value);
    }
    
    /// <remarks/>
    public: [System::Xml::Serialization::XmlIgnoreAttribute]
    property System::Boolean MontoTotalImpuestoSpecified {
        System::Boolean get();
        System::Void set(System::Boolean value);
    }
    
    /// <remarks/>
    public: property System::Decimal TotalFactura {
        System::Decimal get();
        System::Void set(System::Decimal value);
    }
};





inline System::String^  MensajeHacienda::Clave::get() {
    return this->claveField;
}
inline System::Void MensajeHacienda::Clave::set(System::String^  value) {
    this->claveField = value;
}

inline System::String^  MensajeHacienda::NombreEmisor::get() {
    return this->nombreEmisorField;
}
inline System::Void MensajeHacienda::NombreEmisor::set(System::String^  value) {
    this->nombreEmisorField = value;
}

inline MensajeHaciendaTipoIdentificacionEmisor MensajeHacienda::TipoIdentificacionEmisor::get() {
    return this->tipoIdentificacionEmisorField;
}
inline System::Void MensajeHacienda::TipoIdentificacionEmisor::set(MensajeHaciendaTipoIdentificacionEmisor value) {
    this->tipoIdentificacionEmisorField = value;
}

inline System::String^  MensajeHacienda::NumeroCedulaEmisor::get() {
    return this->numeroCedulaEmisorField;
}
inline System::Void MensajeHacienda::NumeroCedulaEmisor::set(System::String^  value) {
    this->numeroCedulaEmisorField = value;
}

inline System::String^  MensajeHacienda::NombreReceptor::get() {
    return this->nombreReceptorField;
}
inline System::Void MensajeHacienda::NombreReceptor::set(System::String^  value) {
    this->nombreReceptorField = value;
}

inline System::Nullable<MensajeHaciendaTipoIdentificacionReceptor > MensajeHacienda::TipoIdentificacionReceptor::get() {
    return this->tipoIdentificacionReceptorField;
}
inline System::Void MensajeHacienda::TipoIdentificacionReceptor::set(System::Nullable<MensajeHaciendaTipoIdentificacionReceptor > value) {
    this->tipoIdentificacionReceptorField = value;
}

inline System::Boolean MensajeHacienda::TipoIdentificacionReceptorSpecified::get() {
    return this->tipoIdentificacionReceptorFieldSpecified;
}
inline System::Void MensajeHacienda::TipoIdentificacionReceptorSpecified::set(System::Boolean value) {
    this->tipoIdentificacionReceptorFieldSpecified = value;
}

inline System::String^  MensajeHacienda::NumeroCedulaReceptor::get() {
    return this->numeroCedulaReceptorField;
}
inline System::Void MensajeHacienda::NumeroCedulaReceptor::set(System::String^  value) {
    this->numeroCedulaReceptorField = value;
}

inline MensajeHaciendaMensaje MensajeHacienda::Mensaje::get() {
    return this->mensajeField;
}
inline System::Void MensajeHacienda::Mensaje::set(MensajeHaciendaMensaje value) {
    this->mensajeField = value;
}

inline System::String^  MensajeHacienda::DetalleMensaje::get() {
    return this->detalleMensajeField;
}
inline System::Void MensajeHacienda::DetalleMensaje::set(System::String^  value) {
    this->detalleMensajeField = value;
}

inline System::Decimal MensajeHacienda::MontoTotalImpuesto::get() {
    return this->montoTotalImpuestoField;
}
inline System::Void MensajeHacienda::MontoTotalImpuesto::set(System::Decimal value) {
    this->montoTotalImpuestoField = value;
}

inline System::Boolean MensajeHacienda::MontoTotalImpuestoSpecified::get() {
    return this->montoTotalImpuestoFieldSpecified;
}
inline System::Void MensajeHacienda::MontoTotalImpuestoSpecified::set(System::Boolean value) {
    this->montoTotalImpuestoFieldSpecified = value;
}

inline System::Decimal MensajeHacienda::TotalFactura::get() {
    return this->totalFacturaField;
}
inline System::Void MensajeHacienda::TotalFactura::set(System::Decimal value) {
    this->totalFacturaField = value;
}
